### ISSUE TITLE
Db-set command not working

### ISSUE THREAD

**Issue by Isa14** [heroku/heroku-connect-plugin#106]
Hi, I'm currently using your plugin and it is very useful! :)
but when I try to use `db-set` command I always get an error before trying to set the database.
<img width="1338" alt="Screen Shot 2020-02-10 at 13 31 40" src="https://user-images.githubusercontent.com/20541218/74170472-b5ff9a80-4c0b-11ea-898c-c3fa296c55e7.png">

However, I could do it through the endpoint using directly curl.

It seems to me that the problem is on this method `fetchKeys` and maybe the error was introduced when doing this change on the `db-set.js` file but I'm not completely sure.
<img width="1213" alt="Screen Shot 2020-02-10 at 13 34 58" src="https://user-images.githubusercontent.com/20541218/74170566-e0e9ee80-4c0b-11ea-8a71-6f3d7fd81ba7.png">

I wanted to let you know about it. Thanks in advance!

**Comment by lambacck** [comment]
@Isa14 are you able to set the db from the Heroku Connect Dashboard?

**Comment by lambacck** [comment]
@Isa14 I recommend you open a support ticket because we'll be able to better diagnose the issue from there.

**Comment by Isa14** [comment]
Hi @lambacck Thank you for your answer!
Yes, I'm able to set the db from the Heroku Connect Dashboard and also using curl like it is described here https://devcenter.heroku.com/articles/heroku-connect-api#step-4-configure-the-database-key-and-schema-for-the-connection

Ok, I don't know if that will help but I will open a support ticket telling them about this plugin.

**Comment by CalgaryMichael** [comment]
I am having the same issue with this function. I ran the same API endpoint that this information is being built from and I saw that there is one entry in the `db_keys` array that has a null value for `addon` (which is expected from the error message). In my situation, this entry was the database endpoint created as part of our Amazon VPC tunnel.

It seems that this could be fixed by including something informational in the `name` value if there is no `addon` variable. Such as:
```js
name: `${key.name} (${key.addon ? key.addon.plan : 'No plan specified')})
```

**Comment by sigmavirus24** [comment]
@CalgaryMichael Except that the only supported configuration for Heroku Connect is Heroku PostgreSQL

**Comment by CalgaryMichael** [comment]
@sigmavirus24 [this](https://devcenter.heroku.com/articles/heroku-redis-via-privatelink#connecting-the-heroku-and-amazon-vpc-endpoints) documentation page outlines the set up for Amazon VPC tunneling. You can see here that it adds a config variable to the Heroku app. This shows up in the `db_keys` section:
```
{
  ...
  "db_keys": [
    {
      "name": "DATABASE_ENDPOINT_<ENDPOINT_ID>_URL",
      "addon": null
    },
    ...
  ]
}
```

This is what is tripping this error.

**Comment by sigmavirus24** [comment]
Ah, I see
