### ISSUE TITLE
add heroku user to plugin

### ISSUE THREAD

**Issue by dickeyxxx** [heroku/heroku-connect-plugin#2]
just in case someone needs to push a patch, it would be good to add the shared heroku account as a collab: https://www.npmjs.com/~heroku

**Comment by gulopine** [comment]
Now that we have a Heroku org, I'd like to move this into org ownership, but I'm not clear on how to do so. Do you have any guidance there?

**Comment by dickeyxxx** [comment]
I think you have to submit a support ticket. Ugh.

**Comment by gulopine** [comment]
I've submitted a request with npm, I'll update this ticket once I've heard something.

**Comment by gulopine** [comment]
> Thanks for emailing. Are you an admin member of the heroku org? If so, you can add the package to the heroku org by clicking on the team you want it on, then "add packages", then "populate from personal packages". You can always change a developer to "team admin" by removing them from the org and re-adding as team admin.

**Comment by dickeyxxx** [comment]
I'm not, that's @rcansley

**Comment by rcansley** [comment]
hi @gulopine - I've made you a Team Admin. Let me know if that works for ya.

@dickeyxxx I have shared the itops (org admin) creds with you in Lastpass. Feel free to go around IT for admin stuff going forward!

**Comment by gulopine** [comment]
With some help from @scottpersinger, we've managed to move the package into the heroku org. Lots of people are now marked as owners and should be able to manage it as necessary.
