### ISSUE TITLE
What does `connect:sf:auth --login` do?

### ISSUE THREAD

**Issue by codingjoe** [heroku/heroku-connect-plugin#85]
Hi there,

What does `connect:sf:auth --login` do?

I see that is passes an argument to the API call, but it is not actually documented as part of the API.
https://devcenter.heroku.com/articles/heroku-connect-api#step-6-authenticate-the-connection-to-your-salesforce-org

Best!
-Joe

**Comment by gulopine** [comment]
Honestly, it does nothing. It looks like it was added here in preparation for a feature that was never developed. I'll get it removed.
