### ISSUE TITLE
Bug: db:set does not work (anymore)

### ISSUE THREAD

**Issue by codingjoe** [heroku/heroku-connect-plugin#92]
```
heroku connect:db:set --schema salesforce --db DATABASE_URL --app "$HEROKU_APP_NAME"
```
produces no `stdout` or `stderr` and the connection remains on `NEW`.

You can reproduce this by simply trying our sample app: https://github.com/Thermondo/django-heroku-connect-sample

**Comment by codingjoe** [comment]
Tested on 0.6.0/latest.

**Comment by codingjoe** [comment]
It does still work in 0.5.0:

```
$ heroku plugins:install heroku-connect-plugin@0.5.0 --force
$ johannes$ heroku connect:db:set --schema salesforce --db DATABASE_URL -a "$HEROKU_APP_NAME"
setting database parameters... done
db_key:      DATABASE_URL
schema_name: salesforce
```

**Comment by codingjoe** [comment]
btw, please tag the 0.6.0 release. Makes debugging simpler ;)

**Comment by codingjoe** [comment]
My best guess at this point is the updated dependencies:
https://gist.github.com/43d413d76cb590fce260ffbd0bde5314

**Comment by sigmavirus24** [comment]
Thanks for the report @codingjoe. v0.6.1 has been released with the fix. 🎉

**Comment by codingjoe** [comment]
Thanks @sigmavirus24 with that I finally managed to setup a full deployment pipeline to provision heroku connect for review apps with SF sandboxes. Awesome!

**Comment by sigmavirus24** [comment]
Woah! That's awesome to hear! I'll pass that along to the team.
